version: "3.8"
services:
  web:
    build: ./app
    image: 775439226894.dkr.ecr.us-east-1.amazonaws.com/moviereview:moviereview_web
    command: gunicorn movrev.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    environment:
      - DB_NAME=movrev_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=movrev.cgwi8bqqh1wy.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-3-233-250-8.compute-1.amazonaws.com
      - VIRTUAL_PORT=8000
  nginx:
    build: ./nginx
    image: 775439226894.dkr.ecr.us-east-1.amazonaws.com/moviereview:moviereview_nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume: null
